cameras:
  - name: hdr_left
    namespace: /gt_box/
    video_device: /dev/video4
    hdr_enable: False
    frame_id: hdr_left
  - name: hdr_front
    namespace: /gt_box/
    video_device: /dev/video2
    hdr_enable: False
    frame_id: hdr_front
  - name: hdr_right
    namespace: /gt_box/
    video_device: /dev/video3
    hdr_enable: False
    frame_id: hdr_right